Added tls settings
vostok/singular.core pull request #23
Opened 2022-08-09 06:38 UTC by HolyPrapor

2022-08-23 12:44 UTC, TGladysheva requested changes

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core.Tests/Tls/SingularHandshakeValidator_Tests.cs
> +        public void Should_not_allow_policy_errors_except_chain_errors(SslPolicyErrors error)
Тест не проверяет то, что задумано: будет false, но в обоих случаях потому что chain == null

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core.Tests/Tls/SingularHandshakeValidator_Tests.cs
> +            handshakeValidator.Verify(null, generated, chain, SslPolicyErrors.RemoteCertificateChainErrors).Should().BeFalse();
Можно еще проверить, что  метод verifier.VerifyChain был вызван, чтобы убедиться, что именно по этому критерию мы получили false, а не по какому то другому

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            if (!certificateChainVerifier.VerifyChain(chain))
Меня тут смутило, что сначала вызывается certificateChainVerifier.VerifyChain, а потом еще какой то verifier. А этот оказывается только отпечатки проверяет. Может его назовем более явно? ThumbprinVerifier. И интерфейс его заодно

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +                ChainPolicy =
Вот тут RevocationFlag = X509RevocationFlag.ExcludeRoot для чего нужен?

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            log.Warn($"Certificate chain was rejected by the provided {nameof(ITlsHandshakeValidator)}.");
А уже стало можно так логи писать, через интерполяцию? Раньше же надо было в строке темплейт, а дальше аргументами параметры.
 Я думала так можно только для .net5 или .net6, т.е с недавних пор. А эта либа может где угодно запускаться

2022-08-23 12:44 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/ThumbprintCertificateChainVerifier.cs
> +                (whitelist.Count == 0 || GetCertificates(chain.ChainElements).Any(x => IsInListOfCertificates(x, whitelist))) &&
В целом, я ничего против такого поведения не имею, пусть остается валидным, если whitelist.Count == 0

2022-08-23 12:46 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            // Certificate (and the whole chain) is trusted by OS. We can safely proceed.
Хм, а если os - windows - не хотим сразу выходить с ее результатом валидации?

2022-08-26 02:26 UTC, HolyPrapor commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            if (!certificateChainVerifier.VerifyChain(chain))
Согласен, нейминги не лучшие.

Текущий интерфейс `ICertificateChainVerifier` на самом деле проверяет, можем ли мы доверять цепочке сертификатов с точки зрения "доверяем ли мы УЦ или нет".

А `verifier`, который тебя смутил, на самом деле проверяет, валидны ли сертификаты сами по себе (Не отозвали ли их? Не истекли ли они?)

А может быть просто вторую часть проверок нужно в другой интерфейс положить? 
Тогда и тудушка ниже будет выполнена.

Могу предложить такие названия: `ICertificateChainAuthorityVerifier` для первого, и `ICertificateChainValidityVerifier` для второго, например.

2022-08-26 02:31 UTC, HolyPrapor commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +                ChainPolicy =
Действительно, здесь должно быть `EntireChain`

2022-08-26 02:34 UTC, HolyPrapor commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            log.Warn($"Certificate chain was rejected by the provided {nameof(ITlsHandshakeValidator)}.");
А тут не `typeof`, тут именно `nameof`, я и хотел вмёржить название в строчку, без свойства (так как оно тут константное)

На < .net6 интерполяция не сработает

Можем поменять на `typeof`, тогда надо привести к структурированному логированию, ага

2022-08-26 02:47 UTC, HolyPrapor commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            // Certificate (and the whole chain) is trusted by OS. We can safely proceed.
Ответил в другом похожем комментарии

2022-08-29 12:39 UTC, TGladysheva commented on Vostok.Singular.Core/Tls/SingularHandshakeValidator.cs
> +            if (!certificateChainVerifier.VerifyChain(chain))
Да, я понимаю, в чем ответственность каждого, мой посыл был именно про нейминги. 
Да, давай сделаем как ты предлагаешь.

2022-09-05 12:44 UTC, merged